
spring:
  application:
    name: global-config

logging:
  level:
    root: INFO

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, env
